### PR TITLE
[FIX] Fix bug in dominance analysis function

### PR DESCRIPTION
**Pull request by liuzhenqi77**
Just realized this was not the same 😱
https://github.com/netneurolab/netneurotools/pull/97#discussion_r571301858

### CODE REVIEW

**Comment by rmarkello** [comment]
Wait really? It's giving me the same thing... Is this maybe a Python version thing?

```python
>>> n_predictor = 4
>>> print([[] for _ in range(n_predictor - 1)])
[[], [], []]
>>> print([[]] * (n_predictor - 1))
[[], [], []]
```

**Comment by rmarkello** [comment]
Ahhhh, just realized—it's just a reference to the same list! Shit, my bad. Sorry about that!!

**Comment by rmarkello** [comment]
@liuzhenqi77 you opened this as a draft PR—I'm assuming you want it merged in though since it's just a quick bug fix. Can you confirm?

**Comment by liuzhenqi77** [comment]
Yes, thanks! :shipit:

**Pull request merged**
